// ── [B] LANGUAGE DATA ────────────────────────────────────────────────────────
// Languages: EN, HI, TE, MR (Marathi added for SUVIDHA C-DAC 2026)

export const LANGS = {
  EN: {
    label: "English", nativeLabel: "English", dir: "ltr",
    welcome: "SUVIDHA",
    sub: "Citizen Services at Your Fingertips",
    tagline: "Smart Urban Virtual Interactive Digital Helpdesk Assistant",
    touch: "Touch Anywhere to Begin",
    selectLang: "Select Your Language",
    selectService: "How may we assist you today?",
    services: ["Electricity", "Gas", "Water & Sanitation", "Municipal Services"],
    serviceIcons: ["⚡", "🔥", "💧", "🏛"],
    serviceDesc: [
      "Bills · Connections · Outages",
      "Connections · Complaints · Safety",
      "Water Bills · Drainage · Waste",
      "Tax · Certificates · Grievances",
    ],
    actions: ["Pay Bill", "New Connection", "File Complaint", "Track Status"],
    actionIcons: ["💳", "🔌", "📋", "🔍"],
    municipalActions: ["Pay Property Tax", "Apply for Certificate", "Register Civic Complaint", "Trade License Services"],
    municipalIcons: ["🏠", "📜", "📝", "🪪"],
    bookCylinder: "Book Cylinder",
    tankerRequest: "Tanker Water Request",
    back: "Back", home: "Home", step: "Step", of: "of",
    billTitle: "Bill Payment",
    connLabel: "Consumer / Connection ID",
    connPlaceholder: "e.g. AP-2024-78543",
    proceed: "Proceed →",
    otpTitle: "Verify Identity",
    otpDesc: "Enter the 6-digit OTP sent to your registered mobile number",
    verify: "Verify & Continue →",
    summaryTitle: "Payment Summary",
    payNow: "Confirm & Pay  ₹1,248",
    successTitle: "Payment Successful",
    successMsg: "Your transaction has been processed",
    refNo: "Reference Number",
    printReceipt: "Print Receipt",
    newTxn: "New Transaction",
    connTitle: "New Connection",
    connStep1: "Your Details", connStep2: "Documents", connStep3: "Confirmation",
    fullName: "Full Name", fullNamePh: "As per Aadhaar card",
    mobile: "Mobile Number", mobilePh: "10-digit mobile number",
    address: "Address", addressPh: "House No., Street, Area, City",
    pinCode: "PIN Code", pinCodePh: "6-digit PIN code",
    uploadAadhaar: "Upload Aadhaar",
    uploadAddress: "Upload Address Proof",
    uploadPhoto: "Upload Photo",
    uploadNote: "Tap to upload · JPG/PNG/PDF · Max 2MB",
    submitConn: "Submit Application →",
    connSuccessTitle: "Application Submitted!",
    connSuccessMsg: "We will visit within 3 working days",
    appNo: "Application Number",
    complaintTitle: "File a Complaint",
    complaintType: "Complaint Type",
    complaintTypes: ["Power Cut", "Low Voltage", "Billing Error", "Meter Fault", "New Connection Delay", "Other"],
    descLabel: "Describe Your Problem",
    descPh: "Please describe the issue in detail…",
    locationLabel: "Your Address / Location",
    locationPh: "Street, Area, Landmark",
    submitComplaint: "Submit Complaint →",
    complaintSuccessTitle: "Complaint Registered!",
    complaintSuccessMsg: "We will resolve your issue within 48 hours",
    compNo: "Complaint Number",
    trackTitle: "Track Your Request",
    trackPlaceholder: "Enter Reference / Application / Complaint No.",
    trackBtn: "Track →",
    trackNotFound: "No record found. Please check the number.",
    trackStatus: "Current Status",
    trackHistory: "Activity Timeline",
    statuses: ["Received", "Under Review", "In Progress", "Resolved"],
    alerts: [
      "Planned maintenance: Sector 7 power outage on 25 Feb, 10AM–2PM",
      "Weather Alert: Heavy rain expected — check drainage advisory",
      "Gas supply restored in Zone 4 — services resumed normally",
      "New connections now processed within 3 working days",
    ],
    increaseFontSize: "Increase text size",
    decreaseFontSize: "Decrease text size",
    highContrast: "High contrast",
    normalContrast: "Normal contrast",
    skipToMain: "Skip to main content",
    langSelectLabel: "Choose your preferred language",
    accessibilityTools: "Accessibility Tools",
  },

  HI: {
    label: "हिंदी", nativeLabel: "हिन्दी", dir: "ltr",
    welcome: "सुविधा",
    sub: "नागरिक सेवाएं, आपकी उँगलियों पर",
    tagline: "स्मार्ट शहरी डिजिटल हेल्पडेस्क सहायक",
    touch: "शुरू करने के लिए स्पर्श करें",
    selectLang: "भाषा चुनें",
    selectService: "आज हम आपकी कैसे मदद करें?",
    services: ["बिजली", "गैस", "जल एवं स्वच्छता", "नगर निगम"],
    serviceIcons: ["⚡", "🔥", "💧", "🏛"],
    serviceDesc: [
      "बिल · कनेक्शन · आउटेज",
      "कनेक्शन · शिकायत · सुरक्षा",
      "जल बिल · नाली · कचरा",
      "कर · प्रमाणपत्र · शिकायत",
    ],
    actions: ["बिल भुगतान", "नया कनेक्शन", "शिकायत दर्ज", "स्टेटस देखें"],
    actionIcons: ["💳", "🔌", "📋", "🔍"],
    municipalActions: ["संपत्ति कर भुगतान", "प्रमाणपत्र के लिए आवेदन", "नागरिक शिकायत दर्ज", "व्यापार लाइसेंस सेवाएं"],
    municipalIcons: ["🏠", "📜", "📝", "🪪"],
    bookCylinder: "सिलेंडर बुक करें",
    tankerRequest: "टैंकर पानी अनुरोध",
    back: "वापस", home: "होम", step: "चरण", of: "का",
    billTitle: "बिल भुगतान",
    connLabel: "उपभोक्ता / कनेक्शन आईडी",
    connPlaceholder: "जैसे AP-2024-78543",
    proceed: "आगे बढ़ें →",
    otpTitle: "पहचान सत्यापित करें",
    otpDesc: "अपने पंजीकृत मोबाइल पर भेजा 6-अंकीय OTP दर्ज करें",
    verify: "सत्यापित करें →",
    summaryTitle: "भुगतान सारांश",
    payNow: "भुगतान करें  ₹1,248",
    successTitle: "भुगतान सफल",
    successMsg: "आपका लेन-देन सफलतापूर्वक हो गया",
    refNo: "संदर्भ संख्या",
    printReceipt: "रसीद प्रिंट करें",
    newTxn: "नया लेन-देन",
    connTitle: "नया कनेक्शन",
    connStep1: "आपकी जानकारी", connStep2: "दस्तावेज़", connStep3: "पुष्टि",
    fullName: "पूरा नाम", fullNamePh: "आधार कार्ड अनुसार",
    mobile: "मोबाइल नंबर", mobilePh: "10 अंकों का मोबाइल नंबर",
    address: "पता", addressPh: "घर नं., गली, क्षेत्र, शहर",
    pinCode: "पिन कोड", pinCodePh: "6 अंकों का पिन",
    uploadAadhaar: "आधार अपलोड करें",
    uploadAddress: "पते का प्रमाण",
    uploadPhoto: "फोटो अपलोड करें",
    uploadNote: "अपलोड करने के लिए टैप करें · JPG/PNG/PDF · अधिकतम 2MB",
    submitConn: "आवेदन जमा करें →",
    connSuccessTitle: "आवेदन सबमिट हो गया!",
    connSuccessMsg: "हम 3 कार्यदिवसों में आएंगे",
    appNo: "आवेदन संख्या",
    complaintTitle: "शिकायत दर्ज करें",
    complaintType: "शिकायत का प्रकार",
    complaintTypes: ["बिजली कटौती", "कम वोल्टेज", "बिलिंग त्रुटि", "मीटर खराबी", "कनेक्शन देरी", "अन्य"],
    descLabel: "समस्या का विवरण",
    descPh: "कृपया समस्या विस्तार से बताएं…",
    locationLabel: "आपका पता / स्थान",
    locationPh: "गली, क्षेत्र, लैंडमार्क",
    submitComplaint: "शिकायत जमा करें →",
    complaintSuccessTitle: "शिकायत दर्ज हो गई!",
    complaintSuccessMsg: "हम 48 घंटों में समाधान करेंगे",
    compNo: "शिकायत संख्या",
    trackTitle: "अपनी स्थिति जांचें",
    trackPlaceholder: "संदर्भ / आवेदन / शिकायत संख्या दर्ज करें",
    trackBtn: "खोजें →",
    trackNotFound: "कोई रिकॉर्ड नहीं मिला। कृपया संख्या जांचें।",
    trackStatus: "वर्तमान स्थिति",
    trackHistory: "गतिविधि",
    statuses: ["प्राप्त", "समीक्षाधीन", "प्रक्रियाधीन", "हल हो गया"],
    alerts: [
      "रखरखाव: सेक्टर 7 में 25 फरवरी 10AM–2PM बिजली कटौती",
      "मौसम चेतावनी: भारी वर्षा संभावित — जल निकासी जांचें",
      "जोन 4 में गैस आपूर्ति बहाल — सेवाएं सामान्य",
      "नए कनेक्शन 3 कार्यदिवसों में पूर्ण होंगे",
    ],
    increaseFontSize: "अक्षर बड़े करें",
    decreaseFontSize: "अक्षर छोटे करें",
    highContrast: "उच्च कंट्रास्ट",
    normalContrast: "सामान्य कंट्रास्ट",
    skipToMain: "मुख्य सामग्री पर जाएं",
    langSelectLabel: "अपनी पसंदीदा भाषा चुनें",
    accessibilityTools: "पहुँच उपकरण",
  },

  TE: {
    label: "తెలుగు", nativeLabel: "తెలుగు", dir: "ltr",
    welcome: "సువిధ",
    sub: "పౌర సేవలు, మీ చేతిలో",
    tagline: "స్మార్ట్ అర్బన్ డిజిటల్ హెల్ప్డెస్క్ అసిస్టెంట్",
    touch: "ప్రారంభించడానికి తాకండి",
    selectLang: "భాష ఎంచుకోండి",
    selectService: "ఈరోజు మీకు ఎలా సహాయపడగలం?",
    services: ["విద్యుత్", "గ్యాస్", "నీరు & పారిశుద్ధ్యం", "మున్సిపల్"],
    serviceIcons: ["⚡", "🔥", "💧", "🏛"],
    serviceDesc: [
      "బిల్లు · కనెక్షన్ · అంతరాయం",
      "కనెక్షన్ · ఫిర్యాదు · భద్రత",
      "నీటి బిల్లు · మురుగు · వ్యర్థం",
      "పన్ను · సర్టిఫికేట్ · ఫిర్యాదు",
    ],
    actions: ["బిల్ చెల్లించు", "కొత్త కనెక్షన్", "ఫిర్యాదు నమోదు", "స్థితి తనిఖీ"],
    actionIcons: ["💳", "🔌", "📋", "🔍"],
    municipalActions: ["ఆస్తి పన్ను చెల్లింపు", "ధృవీకరణ పత్రం కోసం దరఖాస్తు", "పౌర ఫిర్యాదు నమోదు", "వ్యాపార లైసెన్స్ సేవలు"],
    municipalIcons: ["🏠", "📜", "📝", "🪪"],
    bookCylinder: "సిలిండర్ బుక్ చేయండి",
    tankerRequest: "ట్యాంకర్ నీటి అభ్యర్థన",
    back: "వెనక్కి", home: "హోమ్", step: "దశ", of: "లో",
    billTitle: "బిల్ చెల్లింపు",
    connLabel: "వినియోగదారు / కనెక్షన్ ID",
    connPlaceholder: "ఉదా. AP-2024-78543",
    proceed: "కొనసాగించు →",
    otpTitle: "గుర్తింపు ధృవీకరణ",
    otpDesc: "మీ నమోదిత మొబైల్కు వచ్చిన 6-అంకెల OTP నమోదు చేయండి",
    verify: "ధృవీకరించు →",
    summaryTitle: "చెల్లింపు సారాంశం",
    payNow: "నిర్ధారించు & చెల్లించు  ₹1,248",
    successTitle: "చెల్లింపు విజయవంతం",
    successMsg: "మీ లావాదేవీ విజయవంతంగా పూర్తైంది",
    refNo: "సూచన సంఖ్య",
    printReceipt: "రసీదు ముద్రించు",
    newTxn: "కొత్త లావాదేవీ",
    connTitle: "కొత్త కనెక్షన్",
    connStep1: "మీ వివరాలు", connStep2: "పత్రాలు", connStep3: "నిర్ధారణ",
    fullName: "పూర్తి పేరు", fullNamePh: "ఆధార్ కార్డు ప్రకారం",
    mobile: "మొబైల్ నంబర్", mobilePh: "10 అంకెల మొబైల్ నంబర్",
    address: "చిరునామా", addressPh: "ఇంటి నం., వీధి, ప్రాంతం, నగరం",
    pinCode: "పిన్ కోడ్", pinCodePh: "6 అంకెల పిన్ కోడ్",
    uploadAadhaar: "ఆధార్ అప్లోడ్",
    uploadAddress: "చిరునామా రుజువు",
    uploadPhoto: "ఫోటో అప్లోడ్",
    uploadNote: "అప్లోడ్ చేయడానికి తాకండి · JPG/PNG/PDF · గరిష్టం 2MB",
    submitConn: "దరఖాస్తు సమర్పించు →",
    connSuccessTitle: "దరఖాస్తు సమర్పించబడింది!",
    connSuccessMsg: "మేము 3 పని దినాలలో వస్తాము",
    appNo: "దరఖాస్తు సంఖ్య",
    complaintTitle: "ఫిర్యాదు నమోదు",
    complaintType: "ఫిర్యాదు రకం",
    complaintTypes: ["విద్యుత్ కోత", "తక్కువ వోల్టేజ్", "బిల్లింగ్ లోపం", "మీటర్ లోపం", "కనెక్షన్ జాప్యం", "ఇతర"],
    descLabel: "సమస్య వివరణ",
    descPh: "దయచేసి సమస్యను వివరంగా వివరించండి…",
    locationLabel: "మీ చిరునామా / స్థానం",
    locationPh: "వీధి, ప్రాంతం, ల్యాండ్మార్క్",
    submitComplaint: "ఫిర్యాదు సమర్పించు →",
    complaintSuccessTitle: "ఫిర్యాదు నమోదైంది!",
    complaintSuccessMsg: "మేము 48 గంటల్లో పరిష్కరిస్తాము",
    compNo: "ఫిర్యాదు సంఖ్య",
    trackTitle: "మీ స్థితిని తనిఖీ చేయండి",
    trackPlaceholder: "సూచన / దరఖాస్తు / ఫిర్యాదు నంబర్ నమోదు చేయండి",
    trackBtn: "వెతకండి →",
    trackNotFound: "రికార్డ్ కనుగొనబడలేదు. దయచేసి నంబర్ తనిఖీ చేయండి.",
    trackStatus: "ప్రస్తుత స్థితి",
    trackHistory: "కార్యాచరణ",
    statuses: ["స్వీకరించారు", "సమీక్షలో", "ప్రక్రియలో", "పరిష్కరించబడింది"],
    alerts: [
      "నిర్వహణ: సెక్టార్ 7లో 25 ఫిబ్రవరి 10AM–2PM విద్యుత్ అంతరాయం",
      "వాతావరణ హెచ్చరిక: భారీ వర్షాలు — నీటి పారుదల తనిఖీ చేయండి",
      "జోన్ 4లో గ్యాస్ సరఫరా పునరుద్ధరించబడింది",
      "కొత్త కనెక్షన్లు 3 పని దినాలలో పూర్తవుతాయి",
    ],
    increaseFontSize: "అక్షర పరిమాణం పెంచు",
    decreaseFontSize: "అక్షర పరిమాణం తగ్గించు",
    highContrast: "అధిక కాంట్రాస్ట్",
    normalContrast: "సాధారణ కాంట్రాస్ట్",
    skipToMain: "ముఖ్య విషయానికి వెళ్ళు",
    langSelectLabel: "మీకు ఇష్టమైన భాష ఎంచుకోండి",
    accessibilityTools: "ప్రాప్యత సాధనాలు",
  },

  MR: {
    label: "मराठी", nativeLabel: "मराठी", dir: "ltr",
    welcome: "सुविधा",
    sub: "नागरिक सेवा, आपल्या बोटांच्या टोकावर",
    tagline: "स्मार्ट शहरी डिजिटल हेल्पडेस्क सहाय्यक",
    touch: "सुरू करण्यासाठी स्पर्श करा",
    selectLang: "भाषा निवडा",
    selectService: "आज आम्ही तुमची कशी मदत करू?",
    services: ["वीज", "गॅस", "पाणी व स्वच्छता", "महानगरपालिका"],
    serviceIcons: ["⚡", "🔥", "💧", "🏛"],
    serviceDesc: [
      "बिले · जोडणी · खंडित",
      "जोडणी · तक्रार · सुरक्षा",
      "पाणी बिले · गटार · कचरा",
      "कर · प्रमाणपत्र · तक्रार",
    ],
    actions: ["बिल भरा", "नवीन जोडणी", "तक्रार नोंदवा", "स्थिती तपासा"],
    actionIcons: ["💳", "🔌", "📋", "🔍"],
    municipalActions: ["मालमत्ता कर भरणा", "प्रमाणपत्रासाठी अर्ज", "नागरी तक्रार नोंदवा", "व्यापार परवाना सेवा"],
    municipalIcons: ["🏠", "📜", "📝", "🪪"],
    bookCylinder: "सिलेंडर बुक करा",
    tankerRequest: "टँकर पाणी विनंती",
    back: "मागे", home: "मुख्यपृष्ठ", step: "पायरी", of: "पैकी",
    billTitle: "बिल भरणा",
    connLabel: "ग्राहक / जोडणी आयडी",
    connPlaceholder: "उदा. AP-2024-78543",
    proceed: "पुढे जा →",
    otpTitle: "ओळख सत्यापित करा",
    otpDesc: "तुमच्या नोंदणीकृत मोबाईलवर पाठवलेला 6-अंकी OTP प्रविष्ट करा",
    verify: "सत्यापित करा →",
    summaryTitle: "भरणा सारांश",
    payNow: "पुष्टी करा आणि भरा  ₹1,248",
    successTitle: "भरणा यशस्वी",
    successMsg: "तुमचा व्यवहार यशस्वीरीत्या पूर्ण झाला",
    refNo: "संदर्भ क्रमांक",
    printReceipt: "पावती मुद्रित करा",
    newTxn: "नवीन व्यवहार",
    connTitle: "नवीन जोडणी",
    connStep1: "तुमची माहिती", connStep2: "कागदपत्रे", connStep3: "पुष्टी",
    fullName: "पूर्ण नाव", fullNamePh: "आधार कार्डानुसार",
    mobile: "मोबाईल नंबर", mobilePh: "10-अंकी मोबाईल नंबर",
    address: "पत्ता", addressPh: "घर नं., गली, परिसर, शहर",
    pinCode: "पिन कोड", pinCodePh: "6-अंकी पिन कोड",
    uploadAadhaar: "आधार अपलोड करा",
    uploadAddress: "पत्त्याचा पुरावा",
    uploadPhoto: "फोटो अपलोड करा",
    uploadNote: "अपलोड करण्यासाठी टॅप करा · JPG/PNG/PDF · कमाल 2MB",
    submitConn: "अर्ज सादर करा →",
    connSuccessTitle: "अर्ज सादर झाला!",
    connSuccessMsg: "आम्ही 3 कार्यदिवसांत भेट देऊ",
    appNo: "अर्ज क्रमांक",
    complaintTitle: "तक्रार नोंदवा",
    complaintType: "तक्रारीचा प्रकार",
    complaintTypes: ["वीज खंडित", "कमी व्होल्टेज", "बिलिंग त्रुटी", "मीटर बिघाड", "जोडणी विलंब", "इतर"],
    descLabel: "समस्येचे वर्णन",
    descPh: "कृपया समस्या तपशीलवार सांगा…",
    locationLabel: "तुमचा पत्ता / ठिकाण",
    locationPh: "गली, परिसर, खूण",
    submitComplaint: "तक्रार सादर करा →",
    complaintSuccessTitle: "तक्रार नोंदवली!",
    complaintSuccessMsg: "आम्ही 48 तासांत निराकरण करू",
    compNo: "तक्रार क्रमांक",
    trackTitle: "तुमची विनंती तपासा",
    trackPlaceholder: "संदर्भ / अर्ज / तक्रार क्रमांक प्रविष्ट करा",
    trackBtn: "शोधा →",
    trackNotFound: "कोणताही रेकॉर्ड आढळला नाही. कृपया क्रमांक तपासा.",
    trackStatus: "सध्याची स्थिती",
    trackHistory: "कार्य इतिहास",
    statuses: ["प्राप्त", "आढावा घेतला जात आहे", "प्रक्रियेत", "निराकरण झाले"],
    alerts: [
      "देखभाल: सेक्टर 7 मध्ये 25 फेब्रु 10AM–2PM वीज खंडित",
      "हवामान सूचना: मुसळधार पाऊस अपेक्षित — पाण्याचा निचरा तपासा",
      "झोन 4 मध्ये गॅस पुरवठा पूर्ववत — सेवा सामान्य",
      "नवीन जोडण्या 3 कार्यदिवसांत पूर्ण होतात",
    ],
    increaseFontSize: "अक्षरे मोठी करा",
    decreaseFontSize: "अक्षरे लहान करा",
    highContrast: "उच्च कॉन्ट्रास्ट",
    normalContrast: "सामान्य कॉन्ट्रास्ट",
    skipToMain: "मुख्य मजकुरावर जा",
    langSelectLabel: "तुमची पसंतीची भाषा निवडा",
    accessibilityTools: "प्रवेशयोग्यता साधने",
  },
};
